name: SEngineX
version: ${project.version}
main: ru.sscefalix.sEngineX.SEngineX
api-version: '1.21'
authors: [ sscefalix ]
website: sscefalix.ru
description: Плагин "Ядро" для разработки эко-системы плагинов от sscefalix.