name: SXEngine
version: ${project.version}
main: ru.sscefalix.sxEngine.SXEnginePlugin
api-version: '1.21'
authors: [ sscefalix ]
website: sscefalix.ru
description: Плагин "Ядро" для разработки эко-системы плагинов от sscefalix.